version: '3.9'
services:
    postgres:
        image: 'postgres:latest'
        container_name: postgres
        restart: always
        volumes:
            - ./data/postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    api:
        container_name: node-docker
        build:
            dockerfile: Dockerfile
            context: .
        volumes:
            - /app/node_modules
            - ./:/app
        environment:
            - PGPORT=5432
            - PGHOST=postgres
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        command: ['npx', 'nx', 'run', 'node-docker:${NODE_APP_COMMAND}']
        depends_on:
            - postgres

        deploy:
            restart_policy:
                condition: ${NODE_APP_RESTART_POLICY}
                delay: 5s
                max_attempts: ${NODE_APP_RESTART_COUNT} # it is a number but linter complain this is a string
                window: 120s
