#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run pretty-quick # prettify
npm run pre-commit # eslint lint(also include prettify but prettify support more file extensions than eslint, so run prettify first)