name: CI

on:
    push:
        branches: ['main']
    pull_request:
        types: [opened, synchronize]
jobs:
    build:
        if: github.event_name == 'pull_request' || (github.event_name == 'push' && !github.event.pull_request)
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x]
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm run setup
            - run: npm run lint
            - run: npm run type
            - run: npm run build
            - run: npm test
