name: CI

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x]
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm run setup
            - run: npm run lint-ci
            - run: npm run type
            - run: npm run build
            - run: npm test
